COLORS = {
    "primary": "#5551FF",
    "primary_hover": "#4845E4",
    "primary_light": "#7B79FF",
    "primary_bg": "#F0F0FF",
    "success": "#0FA958",
    "danger": "#F24822",
    "warning": "#FFAA00",
    "info": "#18A0FB",
    "bg_dark": "#1E1E1E",
    "bg_medium": "#2C2C2C",
    "bg_light": "#F5F5F5",
    "bg_white": "#FFFFFF",
    "bg_canvas": "#18191B",
    "text_primary": "#000000",
    "text_secondary": "#8E8E93",
    "text_tertiary": "#C7C7CC",
    "text_white": "#FFFFFF",
    "border": "#E5E5EA",
    "divider": "#38383A",
    "box_1": "#FF3B30",
    "box_2": "#FF9500",
    "box_3": "#FFCC00",
    "box_4": "#34C759",
    "box_5": "#5AC8FA",
    "box_6": "#5856D6",
    "box_selected": "#00D4FF",
    "shadow": "rgba(0, 0, 0, 0.1)",
}

THEMES = {
    "dark": {
        "bg_dark": "#1E1E1E",
        "bg_medium": "#2C2C2C",
        "bg_light": "#F5F5F5",
        "bg_white": "#FFFFFF",
        "bg_canvas": "#18191B",
        "text_primary": "#000000",
        "text_secondary": "#8E8E93",
        "text_tertiary": "#C7C7CC",
        "border": "#E5E5EA",
        "divider": "#38383A",
    },
    "light": {
        "bg_dark": "#F5F5F7",
        "bg_medium": "#E5E5EA",
        "bg_light": "#FFFFFF",
        "bg_white": "#FFFFFF",
        "bg_canvas": "#EFEFF4",
        "text_primary": "#000000",
        "text_secondary": "#5C5C5C",
        "text_tertiary": "#8E8E93",
        "border": "#D1D1D6",
        "divider": "#D1D1D6",
    },
}

LANG_MAP = {
    "zh": {},
    "en": {
        "title": "GeckoAI",
        "load_proj": "Load Project",
        "undo": "Undo",
        "redo": "Redo",
        "autolabel": "Red Detection",
        "fuse": "Fuse Boxes",
        "file_info": "File Info",
        "no_img": "No Image",
        "filename": "File",
        "progress": "Progress",
        "boxes": "Boxes",
        "class_mgmt": "Classes",
        "current_class": "Current Class",
        "edit_classes": "Edit Classes",
        "reassign_class": "Reassign Selected Class",
        "clear_labels": "Delete All Labels",
        "add": "Add",
        "rename": "Rename",
        "apply": "Apply",
        "delete_class": "Delete Class",
        "delete_class_confirm": "Delete class '{name}' (ID {idx})?\nLabels with this class in current image will be reassigned.",
        "delete_class_last": "Cannot delete the last class.",
        "class_name": "Class Name",
        "rename_prompt": "Modify '{name}':",
        "add_prompt": "Class name:",
        "current": "Current",
        "to": "To",
        "no_label_selected": "No label selected.",
        "no_classes_available": "No classes available.",
        "theme_light": "Light Mode",
        "theme_dark": "Dark Mode",
        "export_format": "Export All As",
        "ai_tools": "AI Tools",
        "auto_detect": "Auto Detect",
        "learning": "Learning",
        "foundation_mode": "Foundation Assist",
        "propagate": "Propagate",
        "run_detection": "Run Detection",
        "train_from_labels": "Train From Labels",
        "detection_model": "Detection Model",
        "browse_model": "Browse Model",
        "train_range_start": "Start Index (1-based)",
        "train_range_end": "End Index (1-based)",
        "train_epochs": "Epochs",
        "train_imgsz": "Image Size",
        "select_train_output": "Select Training Output Folder",
        "train_no_project": "No dataset loaded.",
        "train_no_labels": "No labeled images found for training.",
        "train_bad_range": "Invalid range. Please input valid start/end index.",
        "train_done": "Training finished.\nOutput: {path}",
        "train_failed": "Training failed: {err}",
        "train_monitor": "Training Monitor",
        "train_status": "Status",
        "train_progress": "Progress",
        "train_eta": "ETA",
        "train_idle": "Idle",
        "train_running": "Running",
        "train_command": "Command",
        "train_already_running": "Training is already running.",
        "use_official_yolo26n": "Use Official yolo26m.pt",
        "export": "Export All",
        "prev": "Previous",
        "next": "Next",
        "shortcuts": "Shortcuts",
        "shortcut_help": "Shortcut Help",
        "dataset": "Dataset",
        "lang_switch": "ZH",
        "delete": "Delete Selected",
        "remove_from_split": "Remove From Split",
        "remove_confirm": "Remove current image from {split}?",
        "remove_done": "Removed: {name}",
        "remove_none": "No image to remove.",
        "restore_from_split": "Restore Deleted Frame",
        "restore_none": "No removed frame found in this split.",
        "restore_title": "Restore Deleted Frame",
        "restore_select": "Select a frame to restore:",
        "restore_done": "Restored: {name}",
        "select_image": "Select Image",
        "startup_choose_source": "Choose Startup Source",
        "startup_prompt": "How do you want to start?",
        "startup_images": "Open Images Folder",
        "startup_yolo": "Open YOLO Dataset",
        "startup_rfdetr": "Open RF-DETR Dataset",
        "startup_skip": "Later",
        "back_to_source": "Back to Source Select",
        "startup_model_cancel_title": "Model Selection Cancelled",
        "startup_model_cancel_msg": "No model selected. Continue with images folder only?",
        "pick_folder_title": "Select Folder",
        "loaded_from": "Loaded {count} images\nFrom: {path}\nSplit: {split}",
        "no_supported_images": "No supported images found (png/jpg/jpeg)\nFolder: {path}",
        "select_export_folder": "Select Export Folder",
        "select_export_parent_folder": "Select Export Parent Folder",
        "select_golden_export_folder": "Select Golden Export Folder",
        "export_create_val_prompt": "Use brightness adjustment to create validation set?",
        "export_val_disabled_cv2": "OpenCV is not available. Validation augmentation skipped.",
        "export_val_done": "Validation set created: {count} images",
        "export_val_empty": "No train images found for validation augmentation.",
        "export_no_project": "No dataset loaded.",
        "golden_export_no_image": "No current image to export.",
        "golden_export_no_label": "Current image has no label txt. Please annotate and save first.",
        "export_done": "Export completed: {count} images\nOutput: {path}",
        "golden_export_done": "Golden folder exported.\nOutput: {path}",
        "export_failed": "Export failed: {err}",
        "golden_export_failed": "Golden export failed: {err}",
    },
}

from ai_labeller.features.lang_utils import normalize_lang_map


# Normalize language map defaults
normalize_lang_map(LANG_MAP)
